import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Roboto', 'system-ui', 'sans-serif'],
        mono: ['Roboto Mono', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        alert: {
          DEFAULT: "hsl(var(--alert))",
          foreground: "hsl(var(--alert-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        "safco-blue": {
          DEFAULT: "hsl(var(--safco-blue))",
          light: "hsl(var(--safco-blue-light))",
          dark: "hsl(var(--safco-blue-dark))",
        },
        "bg-green": {
          DEFAULT: "hsl(var(--background-green))",
          light: "hsl(var(--background-green-light))",
        },
        "emphasis-green": "hsl(var(--emphasis-green))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // V2 Design Tokens
        "v2-hero-bg": "hsl(var(--v2-hero-bg))",
        "v2-blob-a": "hsl(var(--v2-blob-a))",
        "v2-blob-b": "hsl(var(--v2-blob-b))",
        "v2-blob-c": "hsl(var(--v2-blob-c))",
        "v2-headline": "hsl(var(--v2-headline))",
        "v2-headline-accent": "hsl(var(--v2-headline-accent))",
        "v2-subheadline": "hsl(var(--v2-subheadline))",
        "v2-badge-bg": "hsl(var(--v2-badge-bg))",
        "v2-badge-border": "hsl(var(--v2-badge-border))",
        "v2-badge-text": "hsl(var(--v2-badge-text))",
        "v2-badge-icon-bg": "hsl(var(--v2-badge-icon-bg))",
        "v2-trust-label": "hsl(var(--v2-trust-label))",
        "v2-search-bg": "hsl(var(--v2-search-bg))",
        "v2-search-border": "hsl(var(--v2-search-border))",
        "v2-search-focus-border": "hsl(var(--v2-search-focus-border))",
        "v2-search-icon": "hsl(var(--v2-search-icon))",
        "v2-search-text": "hsl(var(--v2-search-text))",
        "v2-search-placeholder": "hsl(var(--v2-search-placeholder))",
        "v2-dropdown-bg": "hsl(var(--v2-dropdown-bg))",
        "v2-dropdown-border": "hsl(var(--v2-dropdown-border))",
        "v2-dropdown-label": "hsl(var(--v2-dropdown-label))",
        "v2-dropdown-icon": "hsl(var(--v2-dropdown-icon))",
        "v2-dropdown-item": "hsl(var(--v2-dropdown-item))",
        "v2-dropdown-item-hover": "hsl(var(--v2-dropdown-item-hover))",
        "v2-cta-secondary": "hsl(var(--v2-cta-secondary))",
        "v2-cta-secondary-border": "hsl(var(--v2-cta-secondary-border))",
        "v2-cta-secondary-hover": "hsl(var(--v2-cta-secondary-hover))",
        "v2-section": "hsl(var(--v2-section))",
        "v2-section-alt": "hsl(var(--v2-section-alt))",
        "v2-section-title": "hsl(var(--v2-section-title))",
        "v2-section-sub": "hsl(var(--v2-section-sub))",
        "v2-card": "hsl(var(--v2-card))",
        "v2-card-border": "hsl(var(--v2-card-border))",
        "v2-card-hover-border": "hsl(var(--v2-card-hover-border))",
        "v2-img-bg": "hsl(var(--v2-img-bg))",
        "v2-brand-label": "hsl(var(--v2-brand-label))",
        "v2-brand-name": "hsl(var(--v2-brand-name))",
        "v2-product-name": "hsl(var(--v2-product-name))",
        "v2-price": "hsl(var(--v2-price))",
        "v2-price-unit": "hsl(var(--v2-price-unit))",
        "v2-timestamp": "hsl(var(--v2-timestamp))",
        "v2-timestamp-icon": "hsl(var(--v2-timestamp-icon))",
        "v2-list-cta-bg": "hsl(var(--v2-list-cta-bg))",
        "v2-list-cta-border": "hsl(var(--v2-list-cta-border))",
        "v2-promo-hero-bg": "hsl(var(--v2-promo-hero-bg))",
        "v2-promo-teal-bg": "hsl(var(--v2-promo-teal-bg))",
        "v2-promo-teal-border": "hsl(var(--v2-promo-teal-border))",
        "v2-promo-teal-title": "hsl(var(--v2-promo-teal-title))",
        "v2-cat-blue": "hsl(var(--v2-cat-blue))",
        "v2-cat-blue-icon": "hsl(var(--v2-cat-blue-icon))",
        "v2-cat-teal": "hsl(var(--v2-cat-teal))",
        "v2-cat-teal-icon": "hsl(var(--v2-cat-teal-icon))",
        "v2-cat-green": "hsl(var(--v2-cat-green))",
        "v2-cat-green-icon": "hsl(var(--v2-cat-green-icon))",
        "v2-cat-purple": "hsl(var(--v2-cat-purple))",
        "v2-cat-purple-icon": "hsl(var(--v2-cat-purple-icon))",
        "v2-cat-orange": "hsl(var(--v2-cat-orange))",
        "v2-cat-orange-icon": "hsl(var(--v2-cat-orange-icon))",
        "v2-cat-red": "hsl(var(--v2-cat-red))",
        "v2-cat-red-icon": "hsl(var(--v2-cat-red-icon))",
        "v2-cat-indigo": "hsl(var(--v2-cat-indigo))",
        "v2-cat-indigo-icon": "hsl(var(--v2-cat-indigo-icon))",
        "v2-trust-blue": "hsl(var(--v2-trust-blue))",
        "v2-trust-teal": "hsl(var(--v2-trust-teal))",
        "v2-trust-teal-icon": "hsl(var(--v2-trust-teal-icon))",
        "v2-trust-green": "hsl(var(--v2-trust-green))",
        "v2-trust-green-icon": "hsl(var(--v2-trust-green-icon))",
        "v2-trust-purple": "hsl(var(--v2-trust-purple))",
        "v2-trust-purple-icon": "hsl(var(--v2-trust-purple-icon))",
        "v2-trust-orange": "hsl(var(--v2-trust-orange))",
        "v2-trust-orange-icon": "hsl(var(--v2-trust-orange-icon))",
        "v2-hub-teal": "hsl(var(--v2-hub-teal))",
        "v2-hub-teal-bg": "hsl(var(--v2-hub-teal-bg))",
        "v2-hub-teal-text": "hsl(var(--v2-hub-teal-text))",
        "v2-hub-green": "hsl(var(--v2-hub-green))",
        "v2-hub-green-bg": "hsl(var(--v2-hub-green-bg))",
        "v2-hub-green-text": "hsl(var(--v2-hub-green-text))",
        "v2-hub-orange": "hsl(var(--v2-hub-orange))",
        "v2-hub-orange-bg": "hsl(var(--v2-hub-orange-bg))",
        "v2-hub-orange-text": "hsl(var(--v2-hub-orange-text))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "slide-in-right": {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "snap-in": {
          "0%": { transform: "scale(1.15)", opacity: "0.5" },
          "70%": { transform: "scale(0.95)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "snap-in": "snap-in 0.25s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
